# github context - 5
name: Run CI
on: [push, pull_request]

jobs:
  github-context_learning:
    runs-on: ubuntu-latest
    steps:
      - name: echo github context
        run: |
          echo "::Github action:: ${{github.action}}"
          echo "::Github event name:: ${{github.event_name}}"
          echo "::Github job:: ${{github.job}}"
          echo "::github actor:: ${{github.actor}}"
          echo "::github workflow:: ${{github.workflow}}"
          echo "::github run id:: ${{github.run_id}}"

  github-context_usage:
    runs-on: ubuntu-latest
    steps:
      - name: echo github context usage
        if: ${{github.actor == 'rpuppali'}}
        run:  echo "Its Raghav"
      - name: echo github context usage
        if: ${{github.actor != 'rpuppali'}}
        run:  echo "Step wont run if condition fails"