name: runSimpleshellCommands
on: [push]

jobs:
  DisplayHelloWorldAndMultilineCommands:
    runs-on: ubuntu-latest
    steps:
      - name: say hello world
        run: echo "hello world"
      - name: multiline statements
        run: |
          pwd
          ls -al
