name : Running_simple_shell_commands
on: [push]

jobs:
    DisplayHelloWorld:
        runs-on: ubuntu-latest
        steps:
          - name: say hello world
            run: echo "hello world"
          - name: multiline statements
            run: |
              node -v
              npm -v
  
    parallelJobOnMacos:
    runs-on: macos-latest
    steps:
        - name: view sw version
          run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: DisplayHelloWorld
    steps:
        - name: echo a string
          run: Write-Output "Windows String"
        - name: echo a string
          run: Write-Output "Skip CI"