name: expression 
# GitHub ignores case when comparing strings.
# when you use expressions in an if conditional, you may omit the ${{ }}
on: [push, workflow_dispatch]

jobs:
  ExpressionsContexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: Expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{null}}
          echo ${{true}}
          echo ${{false}}
          echo ${{true && false}}
          echo ${{ true || (false && true)}}
          echo ${{ 2 == 2}}
          echo ${{ 1 > 2}}
          echo "::String comparison1:: ${{ 'Name'== 'name'}}"
          echo "::String comparison2:: ${{ 'Name'== 'name'}}"
          echo "::contains function::${{contains('Hello world', 'llo')}}"
          echo "::startWith function::${{startsWith('Hello world', 'He')}}"
          echo "::endsWith function::${{endsWith('Hello world', 'ld')}}"
          echo "::format function::${{format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')}}"