name : first_workflow
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "Hello World"
      - name: multiline run-shell-commands
        run: |
          node -v 
          npm -v
          