name: ChangeInShell
on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash
    
jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
    - name: expressions-1
      run: echo ${{'Hello'}}
           echo ${{true}}

