# github context - 5
name: Run CI
on: [push, pull_request]

jobs:
  normal_ci:
    runs-on: ubuntu-latest
    steps:
      - name: SYSOUT
        run: |
          echo "::Github action:: ${{github.action}}"
          echo "::Github event:: ${{github.event}}"
          echo "::Github event name:: ${{github.event_name}}"
          echo ${{github.job}}
          echo ${{github.action_status}}
          echo ${{github.actor}}
          echo ${{github.workflow}}

