name: ChangeInShell
on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
    - name: Display hello world
      run : 
        pwd
  secondjob:
    runs-on: windows-latest
    needs: firstjob
    steps:
    - name: run on pwsh
      shell: pwsh
      run: |
        Get-TimeZone
        Get-Help
   
