name: changeInShell
on: [push]
defaults:
  run:
    shell: bash

jobs:
  runonubunntu:
    runs-on: ubuntu-latest
    steps:
      - name: currentDirectory
        run: |
          pwd
          ls -al
  runonwindows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: currentDirectory
        run: |
          pwd
          ls -al
      