# GITHUB - Information about the workflow run
name: Context
on: [push, workflow_dispatch]
jobs:
  Context_info:
    runs-on: ubuntu-latest
    steps:
      - name: to JSON
        run: |
          echo "::Runner info:: ${{ toJSON(Runner) }}"
          echo "::Runner info:: ${{ toJSON(GITHUB) }}" 
          echo "::job info:: ${{ toJSON(job) }}"
          echo "::Steps info:: ${{ toJSON(steps) }}"
          echo "::Sectets info:: ${{ toJSON(secrets) }}"
          echo "::github.action_path:: ${{ 'github.action_path' }}"