name: running_simple_shell_commands
on: [push]

jobs:
  run-multiline-shell-commands:
    runs-on: ubuntu_latest
    steps:
      - name: dispaly hello world
        run: echo "Hello World"
      - name: multiline shell commands
        run: |
         node -v
         npm -v

