name : aa_workflow5 

on: [push]

jobs:
  display_windows_info:
    runs-on: windows-latest
    steps:
      - name: Display working directory and list files
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display_linux_info2:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory and list files
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

  