name: dependant_jobs
on: [push, workflow_dispatch]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
    - name: Display hello world
      run : echo "Hello world"
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    steps:
    - name: run when first job is successful
      run: |
        ls -l
        pwd