# continue_on_error - true :

name: status check functions
on: [push, pull_request,workflow_dispatch]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Steps -1 
        run: sleep 20
      - name: steps-2
        id: steps2
        continue-on-error: true
        run: exit 1
      - name: Runs on steps -2 failure
        # if: failure()
        if: failure() && steps.steps2.conclusion == 'failure'
        run: echo "step-2 is failed"
      - name: Runs on success
        # this is not required. By default
        if: success()
        run: echo "Runs on only Success"
      - name: Always runs
        # this is not required. By default  if: suceess() || failure()
        if: Always()  
        run: echo "Runs always"
      - name: Runs on cancelled
        if: cancelled()
        run: echo " Runs when cancelled" 

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - name: Job-2
        run: echo "Job-2 run"
      
      