name: Postman to GCP

on: workflow_dispatch

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: matt-ball/newman-action@main              
        with:
          collection: TestAPIONCLI.postman_collectionv1.json
          # environment: postman_environment.json
        # with:
        #   collection: TestAPIONCLI.postman_collectionv1.json
        # #   environment: Testing/Pokemon.postman_environment.json
        #   reporters: cli,htmlextra
        #   reporter-htmlextra-export: report.html