name: changeInDirectory
on: [push]

jobs:
  changeInDirectory:
    runs-on: ubuntu-latest
    steps:
      - name: currentDirectory
        run: |
          pwd
          ls -al
      - name: changeInWorkingDirectory
        working-directory: /home/runner
        run: |
            pwd
            ls -al
            