name: Save API test results to GCP

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the API tests using Newman and uploads the results to GCP
  save-results:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Newman
      - name: Install Newman
        run: |
          sudo npm install -g newman

      # Runs the API tests using Newman and saves the results as a HTML file
      - name: Run API tests
        run: |
          newman run TestAPIONCLI.postman_collectionv1.json -r html --reporter-html-export results.html
