name: expression 
# GitHub ignores case when comparing strings.
# when you use expressions in an if conditional, you may omit the ${{ }}
on: [push]

jobs:
  ExpressionsContexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: Expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{null}}
          echo ${{true}}
          echo ${{false}}
          echo ${{true && false}}
          echo ${{ true || (false && true)}}
          echo ${{ 2 == 2}}
          echo ${{ 1 > 2}}
          echo ${{ 'name'== 'name'}}
          echo "::String comparison-:: ${{ 'Name'== 'name'}}""

          echo "::contains function::${{contains('Hello world', 'llo')}}"
      