name: Usage of actions/github-script

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  save-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: return "Hello Raghav!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"