name: UsageOfcheckoutAction
on: [push]

jobs:
  UsageOfcheckoutAction:
    runs-on: ubuntu-latest
    steps:
    - name: Display
      run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
    - uses: actions/checkout@v3

      
