name: Postman to GCP

on: [push, workflow_dispatch]

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: matt-ball/newman-action@master              
        with:
          collection: TestAPIONCLI.postman_collectionv1.json
      - name: Upload report
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
            path: report.html
            destination: gs://my-bucket/report.html
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}